### ISSUE TITLE
Errors in Splunk 8

### ISSUE THREAD

**Issue by lindonm** [LukeMurphey/splunk-web-input#10]
After install, unable to save config or create inputs. Seeing the following errors in the logs:

ERROR ModularInputs - Unable to initialize modular input "web_input" defined in the app "website_input": Introspecting scheme=web_input: script running failed (exited with code 1)
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':  The script at path=C:\Program Files\Splunk\etc\apps\website_input\bin\website_input_rest_handler.py has thrown an exception=Traceback (most recent call last):
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\bin\runScript.py", line 82, in <module>
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':      exec(open(REAL_SCRIPT_NAME).read())
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':    File "<string>", line 456
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':      except admin.NotFoundException, e:
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':                                    ^
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':  SyntaxError: invalid syntax
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':  Traceback (most recent call last):
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':    File "C:\Program Files\Splunk\bin\runScript.py", line 82, in <module>
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':      exec(open(REAL_SCRIPT_NAME).read())
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':    File "<string>", line 456
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':      except admin.NotFoundException, e:
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':                                    ^
ERROR ScriptRunner - stderr from 'C:\Program Files\Splunk\bin\Python3.exe C:\Program Files\Splunk\bin\runScript.py setup':  SyntaxError: invalid syntax

Environment:
Splunk Enterprise
Version:
8.0.4.1
Build:
ab7a85abaa98
Windows 2019

**Comment by LukeMurphey** [comment]
I have a fix for this which will ship in 4.5.10 shortly.
